# Generated by Django 2.2.9 on 2020-01-31 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='describe',
            field=models.TextField(default='DataFlair'),
        ),
    ]
